### ISSUE TITLE
Minimum version of Visual Studio 2019 ?

### ISSUE THREAD

**Issue by martinboers** [PLCnext/PLCnext_CLI_VS#1]
Is there a minimum version of Visual Studio 2019 required to use this plug-in?

I have heard that version 16.5 or later is required ... is this correct?

**Comment by mluhmann** [comment]
Hello Martin,
yes, the workload 'C++ for Linux Development' in the Visual Studio Installer has a prerequisite of VS 2019 version 16.5. Unfortunately the installer can't resolve this dependency on its own. When the installer tells you it is not possible to resolve a prerequisite, please first update your Visual Studio Version.
