### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ghost** [PLCnext/PLCnext_CLI_VS#3]
Hi

When I try to build the extension I get the error

CSC : error CS2001: Source file '<my path>\..\_Build_\Version.cs' could not be found about six times.

I can see the file is mention in the csproj file, but not in the filesystem

How to fix it?

**Comment by mluhmann** [comment]
Hi,
this looks like an issue in our synchronization to GitHub. We will fix this in future updates. As a workaround you can create the Version.cs file yourself with the following content:
```
internal static class Version
{
    // assembly version number
    internal const string AssemblyVersion = "1.0.0.0";
}
```

**Comment by mluhmann** [comment]
Fixed
