### ISSUE TITLE
An error during creating a C++ project with a name starting with a lowercase letter

### ISSUE THREAD

**Issue by idzm** [PLCnext/PLCnext_CLI_VS#5]
During creating a project with a name starting with a lowercase letter I get this error message:

![error](https://user-images.githubusercontent.com/23375200/118123696-4b846e00-b3fd-11eb-9e1f-1df0a34e5545.png)

Finally created project has no necessary auto-generated source files (*.cpp).

**Comment by mluhmann** [comment]
Hello,
this error is on purpose and should help you to full fill the PLCnext runtime system naming conventions. Your project name has to start with an upper case letter. Otherwise it will not run on the PLC.

https://www.plcnext.help/te/PLCnext_Runtime/PLCnext_Technology_naming_conventions.htm
