### ISSUE TITLE
PLCnext toolchain download link is broken

### ISSUE THREAD

**Issue by vicgerrard** [PLCnext/PLCnext_CLI_VS#6]
File **PLCnext_Toolchain_Windows_2022.0.exe (280 MB)** provided on page [https://www.phoenixcontact.com/qr/2404267/softw](https://www.phoenixcontact.com/qr/2404267/softw) has invalid checksum (real: 49aef2b2d73101ec444b5c65d4f6f8b1087e6fbf053b5aca79f9693e312f07b4, on page: ce9d31a38f794ab5dfa88d34cf6a4918c6ccd282636a35ea69c5ed4c5aee1837) and can not be installed (tried on several PCs):
![image](https://user-images.githubusercontent.com/18083073/166641979-4ee862e4-485c-41a2-914f-049f075443fe.png)
(Error "Invalid access to memory location")

Can you please fix the download link or upload the installer somewhere else.

@martinboers

**Comment by martinboers** [comment]
This is a known issue that is taking far too long to fix (sorry).
You can get a working version of the same installer here:
https://drive.google.com/file/d/1yQAxB3-QYjpHbLpv_sDVVrvwrcf2xjSX/view?usp=sharing
That link will be disabled when the problem is solved on the Phoenix Contact website.

**Comment by mluhmann** [comment]
Fixed, Download is now working. Please reopen. If it happens again.
