### ISSUE TITLE
MINOR: Tooltips appear to be swapped

### ISSUE THREAD

**Issue by martinboers** [PLCnext/PLCnext_CLI_VS#7]
The tooltips on the `Install...` and `Add...` buttons appear to be swapped:

![image](https://user-images.githubusercontent.com/13133969/188634809-eacdde75-1402-4732-9676-fb2df90f2a73.png)

![image](https://user-images.githubusercontent.com/13133969/188634940-43195c24-27ed-453a-8687-f9d763d50e1a.png)

**Comment by mluhmann** [comment]
Will be fixed next version 2023.0
